import Mathlib.RingTheory.MvPolynomial.Ideal
import Mathlib.RingTheory.MvPolynomial.MonomialOrder

variable {n : Type*} [Fintype n] [DecidableEq n]

/-- The monomial ideal generated by the set of monomials {x^α | α ∈ A} -/
def MvPolynomial.monomialIdeal (A : Set (Finsupp n ℕ)) : Ideal (MvPolynomial n ℚ) := by sorry

theorem MonomialOrder.mem_monomialIdeal_iff_divisible (A : Set (Finsupp n ℕ)) (β : Finsupp n ℕ) :
  (MvPolynomial.X ^ β : MvPolynomial n ℚ) ∈ MvPolynomial.monomialIdeal A ↔ 
  ∃ α ∈ A, (MvPolynomial.X ^ α : MvPolynomial n ℚ) ∣ (MvPolynomial.X ^ β : MvPolynomial n ℚ) := by sorry
:= by sorry
