import Mathlib

open Metric EuclideanSpace IntermediateField Module Polynomial
open scoped PiLp Real

noncomputable section

/-- The intermediate field `ℚ(α)` inside `ℂ`, where the real number `α` is embedded in
`ℂ` by the standard real-to-complex algebra map. -/
def ratAdjoinRealInComplex (α : ℝ) : IntermediateField ℚ ℂ :=
  IntermediateField.adjoin ℚ {((algebraMap ℝ ℂ) α)}

/-- The normal closure in `ℂ` of the extension `ℚ(α)/ℚ`. -/
def normalClosureOfRatAdjoin (α : ℝ) : IntermediateField ℚ ℂ :=
  IntermediateField.normalClosure ℚ (ratAdjoinRealInComplex α) ℂ

/-- A natural number is a power of two. -/
def IsPowerOfTwo (n : ℕ) : Prop :=
  ∃ k : ℕ, n = 2 ^ k

/-- One step in the field-theoretic model of compass-and-straightedge constructibility:
the next field contains the previous one and has relative degree one or two. -/
def IsAtMostQuadraticStep (K L : IntermediateField ℚ ℂ) : Prop :=
  K ≤ L ∧
    (IntermediateField.relfinrank K L = 1 ∨ IntermediateField.relfinrank K L = 2)

/-- Field-theoretic constructibility over `ℚ`: a real number is constructible when its
image in `ℂ` lies in a finite tower of intermediate fields over `ℚ`, starting from `ℚ`,
with each step of relative degree at most two. -/
def IsConstructible (α : ℝ) : Prop :=
  ∃ (n : ℕ) (K : Fin (n + 1) → IntermediateField ℚ ℂ),
    K (0 : Fin (n + 1)) = ⊥ ∧
      (∀ i : Fin n, IsAtMostQuadraticStep (K i.castSucc) (K i.succ)) ∧
        ((algebraMap ℝ ℂ) α) ∈ K (Fin.last n)

/-- The degree `[K : ℚ]` where `K` is the normal closure in `ℂ` of `ℚ(α)/ℚ`. -/
def normalClosureDegree (α : ℝ) : ℕ :=
  Module.finrank ℚ (normalClosureOfRatAdjoin α)

/--
Source theorem `constructible_iff` from `docs/source.tex`.

Source proof: if the normal closure has degree `2^a`, take a composition series of the
Galois group with subquotients of order two; Galois correspondence gives a tower of fixed
fields with quadratic steps down to `K`, so `α` is constructible. Conversely, if `α` is
constructible by a finite tower of quadratic extensions, each conjugate of `α` is also in
such a tower; adjoining the finitely many conjugates keeps the total degree a power of two,
so the normal closure degree is a power of two.

Prover notes: unfold `normalClosureDegree`, `normalClosureOfRatAdjoin`, `IsConstructible`,
`IsAtMostQuadraticStep`, and `IsPowerOfTwo`; the source proof expects finite Galois theory,
composition series for finite `2`-groups, and multiplicativity of finite tower degrees.
-/
theorem constructible_iff (α : ℝ) :
    IsConstructible α ↔ IsPowerOfTwo (normalClosureDegree α) := by
  sorry

/-- A Fermat prime is a prime of the form `2^(2^a) + 1`. -/
def IsFermatPrime (p : ℕ) : Prop :=
  Nat.Prime p ∧ ∃ a : ℕ, p = 2 ^ (2 ^ a) + 1

/-- A natural number is a product of a power of two and a finite set of distinct Fermat
primes. Distinctness is represented by the `Finset`. -/
def IsProductOfPowerOfTwoAndDistinctFermatPrimes (n : ℕ) : Prop :=
  ∃ (c : ℕ) (S : Finset ℕ),
    (∀ p ∈ S, IsFermatPrime p) ∧ n = 2 ^ c * S.prod id

/-- Field-theoretic constructibility of the angle `2π/n`, represented by constructibility
of its cosine. The guard `0 < n` records the source's implicit positive-integer domain. -/
def IsAngleConstructible (n : ℕ) : Prop :=
  0 < n ∧ IsConstructible (Real.cos (2 * Real.pi / (n : ℝ)))

/-- Companion bridge for the source parenthetical statement that constructibility of the
angle `2π/n` is equivalent to constructibility of the regular `n`-gon. -/
def IsRegularNGonConstructible (n : ℕ) : Prop :=
  IsAngleConstructible n

/--
Source theorem `cyclotomic_angle_constructible_iff` from `docs/source.tex`.

Source proof: for `n = 1, 2` the claim is clear. For `n ≥ 3`, take a primitive root
`ζ_n = exp(2π i/n)`; then `cos(2π/n) = (ζ_n + ζ_n⁻¹)/2`. The cyclotomic extension has
`[ℚ(ζ_n):ℚ] = φ(n)`, and the real subfield generated by `ζ_n + ζ_n⁻¹` has index two in
`ℚ(ζ_n)`, so its degree over `ℚ` is `φ(n)/2`. Constructibility forces this degree, hence
`φ(n)`, to be a power of two, which is exactly the classification that `n` is a power of
`2` times distinct Fermat primes. Conversely, for such `n`, `φ(n)` is a power of two; the
fixed field of complex conjugation is `ℚ(ζ_n + ζ_n⁻¹)`, and the previous theorem gives
constructibility of `ζ_n + ζ_n⁻¹`, hence of `cos(2π/n)`.

Prover notes: use cyclotomic degree `φ(n)`, the real subfield fixed by conjugation, the
classification `φ(n)` power-of-two iff `n` is a power of two times distinct Fermat primes,
and then apply `constructible_iff` to the relevant real generator.
-/
theorem cyclotomic_angle_constructible_iff (n : ℕ) :
    IsAngleConstructible n ↔ IsProductOfPowerOfTwoAndDistinctFermatPrimes n := by
  sorry
