import Mathlib.Data.Real.Basic
import Mathlib.Algebra.MvPolynomial.PDeriv
import Mathlib.RingTheory.Ideal.Span
import Mathlib.RingTheory.Nullstellensatz

/-!
# ShadowBench algebra/L2/alg_gen_L2_004

This file formalizes the source problem in `docs/source.tex`.  We use
`MvPolynomial (Fin 2) ℝ` for the real polynomial ring `ℝ[x,y]`, with
`xPoly` and `yPoly` representing the two coordinate variables.
-/

noncomputable section

/-- The polynomial ring `ℝ[x,y]`, represented as multivariate polynomials in two variables. -/
abbrev PolyRing : Type := MvPolynomial (Fin 2) ℝ

/-- The source variable `x`, represented by the `0`-th multivariate polynomial variable. -/
def xPoly : PolyRing := MvPolynomial.X (0 : Fin 2)

/-- The source variable `y`, represented by the `1`-st multivariate polynomial variable. -/
def yPoly : PolyRing := MvPolynomial.X (1 : Fin 2)

/-- The ideal `J = ⟨x^2 + y^2 - 1, y - 1⟩` in `ℝ[x,y]`. -/
def J : Ideal PolyRing :=
  Ideal.span ({xPoly ^ 2 + yPoly ^ 2 - 1, yPoly - 1} : Set PolyRing)

/--
Source proof: take the witness `f = x`.  The common zeros of `J` satisfy
`y - 1 = 0` and `x^2 + y^2 - 1 = 0`, hence are only the point `(0,1)`,
so the coordinate polynomial `x` vanishes on `V(J)`.  To show `x ∉ J`,
specialize `y ↦ 1`; the generators map into `⟨x^2⟩`, while `x` itself is
not in `⟨x^2⟩`.

Prover notes: use witness `xPoly`.  `MvPolynomial.mem_vanishingIdeal_iff`,
`MvPolynomial.mem_zeroLocus_iff`, and `MvPolynomial.zeroLocus_span` expose
the two generator equations for the vanishing-ideal part.  For nonmembership,
formalize the specialization homomorphism sending `yPoly` to `1` and compare
with the one-variable ideal generated by `X^2`.
-/
theorem exists_vanishingIdeal_zeroLocus_not_mem_J :
    ∃ f : PolyRing,
      f ∈ MvPolynomial.vanishingIdeal ℝ (MvPolynomial.zeroLocus ℝ J) ∧ f ∉ J := by
  refine ⟨xPoly, ?_, ?_⟩
  · have hx2J : xPoly ^ 2 ∈ J := by
      have hg1 : xPoly ^ 2 + yPoly ^ 2 - 1 ∈ J := by
        rw [J]
        exact Ideal.subset_span (by simp)
      have hg2 : yPoly - 1 ∈ J := by
        rw [J]
        exact Ideal.subset_span (by simp)
      have hcomb : (xPoly ^ 2 + yPoly ^ 2 - 1) - (yPoly + 1) * (yPoly - 1) = xPoly ^ 2 := by
        ring
      rw [← hcomb]
      exact Ideal.sub_mem _ hg1 (Ideal.mul_mem_left _ _ hg2)
    have hxrad : xPoly ∈ J.radical := by
      rw [Ideal.mem_radical_iff]
      exact ⟨2, hx2J⟩
    exact (MvPolynomial.radical_le_vanishingIdeal_zeroLocus (K := ℝ) J) hxrad
  · intro hxJ
    let pt : Fin 2 → ℝ := fun i => if i = (0 : Fin 2) then 0 else 1
    let K : Ideal PolyRing :=
      { carrier := {p | MvPolynomial.aeval pt p = 0 ∧
          MvPolynomial.aeval pt (MvPolynomial.pderiv (0 : Fin 2) p) = 0}
        zero_mem' := by
          simp
        add_mem' := by
          intro p q hp hq
          constructor
          · calc
              MvPolynomial.aeval pt (p + q) =
                  MvPolynomial.aeval pt p + MvPolynomial.aeval pt q := by
                rw [map_add]
              _ = 0 := by
                rw [hp.1, hq.1, zero_add]
          · calc
              MvPolynomial.aeval pt (MvPolynomial.pderiv (0 : Fin 2) (p + q)) =
                  MvPolynomial.aeval pt (MvPolynomial.pderiv (0 : Fin 2) p +
                    MvPolynomial.pderiv (0 : Fin 2) q) := by
                rw [map_add]
              _ = MvPolynomial.aeval pt (MvPolynomial.pderiv (0 : Fin 2) p) +
                  MvPolynomial.aeval pt (MvPolynomial.pderiv (0 : Fin 2) q) := by
                rw [map_add]
              _ = 0 := by
                rw [hp.2, hq.2, zero_add]
        smul_mem' := by
          intro a p hp
          constructor
          · calc
              MvPolynomial.aeval pt (a • p) = MvPolynomial.aeval pt (a * p) := by
                rw [smul_eq_mul]
              _ = MvPolynomial.aeval pt a * MvPolynomial.aeval pt p := by
                rw [map_mul]
              _ = 0 := by
                rw [hp.1, mul_zero]
          · calc
              MvPolynomial.aeval pt (MvPolynomial.pderiv (0 : Fin 2) (a • p)) =
                  MvPolynomial.aeval pt (MvPolynomial.pderiv (0 : Fin 2) (a * p)) := by
                rw [smul_eq_mul]
              _ = MvPolynomial.aeval pt (MvPolynomial.pderiv (0 : Fin 2) a * p +
                    a * MvPolynomial.pderiv (0 : Fin 2) p) := by
                rw [MvPolynomial.pderiv_mul]
              _ = MvPolynomial.aeval pt (MvPolynomial.pderiv (0 : Fin 2) a * p) +
                    MvPolynomial.aeval pt (a * MvPolynomial.pderiv (0 : Fin 2) p) := by
                rw [map_add]
              _ = (MvPolynomial.aeval pt (MvPolynomial.pderiv (0 : Fin 2) a) *
                    MvPolynomial.aeval pt p) +
                    (MvPolynomial.aeval pt a *
                      MvPolynomial.aeval pt (MvPolynomial.pderiv (0 : Fin 2) p)) := by
                rw [map_mul, map_mul]
              _ = 0 := by
                rw [hp.1, hp.2, mul_zero, mul_zero, zero_add] }
    have hJleK : J ≤ K := by
      rw [J]
      apply Ideal.span_le.mpr
      intro p hp
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hp
      rcases hp with hp | hp
      · subst p
        constructor
        · simp [pt, xPoly, yPoly]
        · simp [pt, xPoly, yPoly]
      · subst p
        constructor
        · simp [pt, yPoly]
        · simp [pt, yPoly]
    have hxK : xPoly ∈ K := hJleK hxJ
    have hder : MvPolynomial.aeval pt (MvPolynomial.pderiv (0 : Fin 2) xPoly) = 0 := hxK.2
    simp [xPoly, pt] at hder
