import Mathlib.Data.Real.Basic
import Mathlib.RingTheory.Ideal.Span
import Mathlib.RingTheory.Nullstellensatz

/-!
# ShadowBench algebra/L2/alg_gen_L2_004

This file formalizes the source problem in `docs/source.tex`.  We use
`MvPolynomial (Fin 2) ℝ` for the real polynomial ring `ℝ[x,y]`, with
`xPoly` and `yPoly` representing the two coordinate variables.
-/

noncomputable section

/-- The polynomial ring `ℝ[x,y]`, represented as multivariate polynomials in two variables. -/
abbrev PolyRing : Type := MvPolynomial (Fin 2) ℝ

/-- The source variable `x`, represented by the `0`-th multivariate polynomial variable. -/
def xPoly : PolyRing := MvPolynomial.X (0 : Fin 2)

/-- The source variable `y`, represented by the `1`-st multivariate polynomial variable. -/
def yPoly : PolyRing := MvPolynomial.X (1 : Fin 2)

/-- The ideal `J = ⟨x^2 + y^2 - 1, y - 1⟩` in `ℝ[x,y]`. -/
def J : Ideal PolyRing :=
  Ideal.span ({xPoly ^ 2 + yPoly ^ 2 - 1, yPoly - 1} : Set PolyRing)

/--
Source proof: take the witness `f = x`.  The common zeros of `J` satisfy
`y - 1 = 0` and `x^2 + y^2 - 1 = 0`, hence are only the point `(0,1)`,
so the coordinate polynomial `x` vanishes on `V(J)`.  To show `x ∉ J`,
specialize `y ↦ 1`; the generators map into `⟨x^2⟩`, while `x` itself is
not in `⟨x^2⟩`.

Prover notes: use witness `xPoly`.  `MvPolynomial.mem_vanishingIdeal_iff`,
`MvPolynomial.mem_zeroLocus_iff`, and `MvPolynomial.zeroLocus_span` expose
the two generator equations for the vanishing-ideal part.  For nonmembership,
formalize the specialization homomorphism sending `yPoly` to `1` and compare
with the one-variable ideal generated by `X^2`.
-/
theorem exists_vanishingIdeal_zeroLocus_not_mem_J :
    ∃ f : PolyRing,
      f ∈ MvPolynomial.vanishingIdeal ℝ (MvPolynomial.zeroLocus ℝ J) ∧ f ∉ J := by
  sorry
