import Mathlib.AlgebraicGeometry.Morphisms.FiniteType
import Mathlib.AlgebraicGeometry.Morphisms.QuasiCompact
import Mathlib.AlgebraicGeometry.AffineScheme
import Mathlib.RingTheory.FiniteType
import Mathlib.CategoryTheory.Opposites

open CategoryTheory Opposite
open AlgebraicGeometry

/--
Source `FiniteType` (docs/source.tex, lines 17-28): a morphism of schemes is of finite type
when the target has an affine open cover whose inverse images admit finite affine open covers
with finite-type coordinate algebras over the corresponding target coordinates.

Formalization bridge: Mathlib provides `LocallyOfFiniteType` for the local finite-type ring-map
condition and `QuasiCompact` for the finite-cover/quasi-compact part. Their conjunction is used
as the standard finite-type morphism predicate matching the source definition.
-/
def FiniteType {X Y : Scheme} (f : X ⟶ Y) : Prop :=
  LocallyOfFiniteType f ∧ QuasiCompact f

/--
Source theorem `affineFiniteType_iff_globalSectionsFiniteType` (docs/source.tex, lines 30-44):
for affine schemes `X` and `Y`, a morphism `f : X ⟶ Y` is of finite type iff the induced
homomorphism on global sections makes `Γ(X, 𝒪_X)` a finite-type algebra over `Γ(Y, 𝒪_Y)`.

Source proof: sufficiency is immediate from the affine cover by the whole target. Necessity first
shows the defining affine-cover condition is stable under replacing an affine target open by an
affine open subset via distinguished opens and localization. Applying this to `Y` gives a finite
affine open cover of `X`; refine it to principal opens `D(g_i)` so the localized rings `B_{g_i}`
are finite type over `A = Γ(Y, 𝒪_Y)`. Choose finite generators with common denominators,
use that the `g_i` generate the unit ideal, and clear denominators to show every `b ∈ B` lies in
the finite `A`-subalgebra generated by the chosen numerators, the `g_i`, and coefficients `h_i`
with `∑ h_i g_i = 1`.

Prover notes: unfold `FiniteType`; use Mathlib's affine-local finite-type morphism API,
especially `LocallyOfFiniteType`, `QuasiCompact`, `Scheme.Hom.appTop`, and
`RingHom.FiniteType` for the induced global-section ring homomorphism.
-/
theorem affineFiniteType_iff_globalSectionsFiniteType {X Y : Scheme}
    (hX : IsAffine X) (hY : IsAffine Y) (f : X ⟶ Y) :
    FiniteType f ↔ RingHom.FiniteType f.appTop.hom := by
  sorry
