import Mathlib.Topology.Spectral.Basic
import Mathlib.Topology.JacobsonSpace
import Mathlib.Data.Set.Card

open Set Topology

/-- The subbasis for the constructible topology consists of compact open subsets 
    and their complements. -/
def constructibleSubbasis (X : Type*) [TopologicalSpace X] : Set (Set X) := 
  {s | ∃ t : Set X, IsOpen t ∧ IsCompact t ∧ s = t} ∪ 
  {s | ∃ t : Set X, IsOpen t ∧ IsCompact t ∧ s = tᶜ}

/-- The constructible topology on a topological space X is the topology generated by the subbasis
consisting of compact open subsets of X and their complements. -/
noncomputable def constructibleTopology (X : Type*) [TopologicalSpace X] : TopologicalSpace X := 
  Topology.generate (constructibleSubbasis X)

/-- Let X be a topological space. The constructible topology on X is the topology generated by
the subbasis consisting of compact open subsets of X and their complements. -/
theorem isCompact_sInter_of_subset_constructibleTopologySubbasis (X : Type*) [TopologicalSpace X] :
  -- This theorem is actually redundant with the definition above,
  -- but included to match the problem statement format
  true := sorry

/-- If X is a quasi-separated, quasi-sober, prespectral and quasi-compact topological space, 
then X is still quasi-compact in the constructible topology. -/
theorem compactSpace_withConstructibleTopology (X : Type*) [TopologicalSpace X]
  (h_quasi_separated : ∀ s t : Set X, IsClosed s → IsClosed t → Disjoint s t →
                       ∀ u v : Set X, IsOpen u → IsOpen v → s ⊆ u → t ⊆ v → Disjoint u v)
  (h_quasi_sober : ∀ x : X, IsClosed ({x}) → IsOpen ({x}))
  (h_prespectral : ∀ s : Set X, IsClosed s → 
                  s = ⋂₀ {u : Set X | IsOpen u ∧ s ⊆ u})
  (h_quasi_compact : IsCompact univ) :
  IsCompact univ@(constructibleTopology X) := sorry
