import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.RingTheory.Noetherian.Defs
import Mathlib.RingTheory.Polynomial.Basic
import Mathlib.RingTheory.PrincipalIdealDomain

/-!
# ShadowBench algebra/L2/alg_gen_L2_016

Formalization draft for `docs/source.tex`. See `ShadowBench/Source/Blueprint.md`
for the source map, statement-fidelity notes, and proof handoff notes.
-/

/--
Source: `docs/source.tex`, theorem `span_pow_card_mul_le_span_image_pow` (lines 17--25).
The source states that for a finite listed set `s = {g₁, ..., gᵣ}` in
`k[x₁, ..., xₙ]`, with `J = ⟨s⟩` and `M ≥ 0`, one has
`J^(r*M) ⊆ ⟨g^M | g ∈ s⟩`.  Lean represents the finite listed set by a
nonempty `Finset`; `s.card` is the source integer `r`.

Source proof: no proof text is present in the source file.
Proof sketch: powers of `Ideal.span (s : Set R)` are generated by products of
`s.card * M` generators from `s`.  By pigeonhole, one generator occurs at least
`M` times in every such product, so the product is divisible by some `g^M` with
`g ∈ s`, hence lies in the ideal generated by the `M`th powers.  For `M = 0`,
use `hs : s.Nonempty` so the right-hand span contains `1 = g^0`.
-/
theorem span_pow_card_mul_le_span_image_pow
    (k : Type*) [Field k] (n : ℕ)
    (s : Finset (MvPolynomial (Fin n) k)) (hs : s.Nonempty) (M : ℕ) :
    let J : Ideal (MvPolynomial (Fin n) k) :=
      Ideal.span (s : Set (MvPolynomial (Fin n) k))
    J ^ (s.card * M) ≤
      Ideal.span (Set.image (fun g : MvPolynomial (Fin n) k => g ^ M)
        (s : Set (MvPolynomial (Fin n) k))) := by
  sorry
