import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.RingTheory.Noetherian.Defs
import Mathlib.RingTheory.Polynomial.Basic
import Mathlib.RingTheory.PrincipalIdealDomain

/-!
# ShadowBench algebra/L2/alg_gen_L2_016

Formalization draft for `docs/source.tex`. See `ShadowBench/Source/Blueprint.md`
for the source map, statement-fidelity notes, and proof handoff notes.
-/

/--
Source: `docs/source.tex`, theorem `span_pow_card_mul_le_span_image_pow` (lines 17--25).
The source states that for a finite listed set `s = {g₁, ..., gᵣ}` in
`k[x₁, ..., xₙ]`, with `J = ⟨s⟩` and `M ≥ 0`, one has
`J^(r*M) ⊆ ⟨g^M | g ∈ s⟩`.  Lean represents the finite listed set by a
nonempty `Finset`; `s.card` is the source integer `r`.

Source proof: no proof text is present in the source file.
Proof sketch: powers of `Ideal.span (s : Set R)` are generated by products of
`s.card * M` generators from `s`.  By pigeonhole, one generator occurs at least
`M` times in every such product, so the product is divisible by some `g^M` with
`g ∈ s`, hence lies in the ideal generated by the `M`th powers.  For `M = 0`,
use `hs : s.Nonempty` so the right-hand span contains `1 = g^0`.
-/
theorem span_pow_card_mul_le_span_image_pow
    (k : Type*) [Field k] (n : ℕ)
    (s : Finset (MvPolynomial (Fin n) k)) (hs : s.Nonempty) (M : ℕ) :
    let J : Ideal (MvPolynomial (Fin n) k) :=
      Ideal.span (s : Set (MvPolynomial (Fin n) k))
    J ^ (s.card * M) ≤
      Ideal.span (Set.image (fun g : MvPolynomial (Fin n) k => g ^ M)
        (s : Set (MvPolynomial (Fin n) k))) := by
  classical
  dsimp only
  have aux : ∀ (u : Finset (MvPolynomial (Fin n) k)), u.Nonempty →
      (Ideal.span (u : Set (MvPolynomial (Fin n) k))) ^ (u.card * M) ≤
        Ideal.span (Set.image (fun g : MvPolynomial (Fin n) k => g ^ M)
          (u : Set (MvPolynomial (Fin n) k))) := by
    intro u
    refine Finset.induction_on u ?empty ?insert
    · intro hu
      rcases hu with ⟨x, hx⟩
      simp at hx
    · intro a t hat IH hu
      rcases t.eq_empty_or_nonempty with htempty | htne
      · subst t
        simp [Ideal.span_singleton_pow]
      · let Ia : Ideal (MvPolynomial (Fin n) k) := Ideal.span ({a} : Set (MvPolynomial (Fin n) k))
        let It : Ideal (MvPolynomial (Fin n) k) := Ideal.span (t : Set (MvPolynomial (Fin n) k))
        let P : Ideal (MvPolynomial (Fin n) k) :=
          Ideal.span (Set.image (fun g : MvPolynomial (Fin n) k => g ^ M)
            ((insert a t : Finset (MvPolynomial (Fin n) k)) : Set (MvPolynomial (Fin n) k)))
        have hspan :
            Ideal.span (((insert a t : Finset (MvPolynomial (Fin n) k)) :
              Set (MvPolynomial (Fin n) k))) = Ia ⊔ It := by
          simpa [Ia, It] using (Ideal.span_insert a (t : Set (MvPolynomial (Fin n) k)))
        have hpow_a : Ia ^ M ≤ P := by
          rw [Ideal.span_singleton_pow]
          exact Ideal.span_mono (by
            intro x hx
            rcases hx with rfl
            exact ⟨a, by simp, rfl⟩)
        have hpow_t : It ^ (t.card * M) ≤ P := by
          exact (IH htne).trans (Ideal.span_mono (by
            intro x hx
            rcases hx with ⟨g, hg, rfl⟩
            exact ⟨g, by simp [hg], rfl⟩))
        have hsup : (Ia ⊔ It) ^ (M + t.card * M) ≤ P := by
          exact
            (Ideal.sup_pow_add_le_pow_sup_pow (I := Ia) (J := It) (n := M)
              (m := t.card * M)).trans
            (sup_le hpow_a hpow_t)
        calc
          (Ideal.span (((insert a t : Finset (MvPolynomial (Fin n) k)) :
            Set (MvPolynomial (Fin n) k)))) ^ ((insert a t).card * M)
              = (Ia ⊔ It) ^ (M + t.card * M) := by
                rw [hspan]
                congr 1
                rw [Finset.card_insert_of_notMem hat]
                simp [Nat.add_mul, Nat.add_comm]
          _ ≤ P := hsup
  exact aux s hs
